### ISSUE TITLE
How to change from f° to c°

### ISSUE THREAD

**Issue by mickandkez** [kdorff/esphome#1]
how do i make a change so i can display c° or % in here
sprintf(buffer, "%.0f°", back_yard_temperature->state);
cheers

**Comment by kevindorff** [comment]
This code currently has no opinion about the value being displayed. It asks Home Assistant for the sensor's temperature value. my sensor reports readings in degrees Fahrenheit, so that is what is displayed. I'd think you'd adjust the sensor to read the temperature in C vs F. 

If JUST reporting the floating point value that is coming from Home Assistant isn't good enough for you, say you want to keep your sensor in degress F but display in degress C, you might change the code to be similar to but maybe not exactly (I'm not a compiler, so the code may have simple problems)

```
   float tempAsF =  back_yard_temperature->state;
   float tempAsC = (tempAsF − 32) * (5/9);
   sprintf(buffer, "%.0f°", tempAsC);
```

Or if the value came in as a percentage, as I assume you weren't referring to percentage of temperature? But either way, if the value comes in as 0.5 and you want to display it as 50% you could do something like

```
   float rawPer =  back_yard_temperature->state;
   float scaledPer = rawPer * 100;
   sprintf(buffer, "%.0f%%", scaledPer);
```

 where the  `%%` instructions sprintf to print the `%` character.

**Comment by kdorff** [comment]
This code currently has no opinion about the value being displayed. It asks Home Assistant for the associated sensor's value, which in my case, the sensor is a temperature sensor which reports readings in degrees Fahrenheit. So that is what is displayed. I'd think you'd want to adjust the sensor to read the appropriate unit C vs F, and not adjust it here.

But, yes, you can (and with percentages, you probably would).

If JUST reporting the floating point value that is coming from Home Assistant isn't good enough for you, say you want to keep your sensor in degress F but display in degress C, you might change the code to be similar to but maybe not exactly (I'm not a compiler, so the code may have simple problems)

```
   float tempAsF =  back_yard_temperature->state;
   float tempAsC = (tempAsF − 32) * (5/9);
   sprintf(buffer, "%.0f°", tempAsC);
```

Or if the value came in as a percentage, as I assume you weren't referring to percentage of temperature? But either way, if the value comes in as 0.5 and you want to display it as 50% you could do something like

```
   float rawPer =  back_yard_temperature->state;
   float scaledPer = rawPer * 100;
   sprintf(buffer, "%.0f%%", scaledPer);
```

where the `%%` instructions `sprintf` to print the `%` character.
